1 html
LizaY47/Hw pull request #1
Opened 2024-07-02 08:06 UTC by LizaY47

2024-07-02 08:30 UTC, GitEsense requested changes
С формой всё хорошо, по блогу оставил замечания, обратите внимание и внесите корректировки, чтобы дальше уже Вам было проще

2024-07-02 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +                <li>Backend</li>
1. Все элементы списка являются ссылками
2. Первый элемент (В Мой блог) - это так же ссылка, но это в первую очередь логотип, хорошо было бы вынести за nav блок, т.к. это не элемент навигационного меню

2024-07-02 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +            </form>
Эта форма поиска идёт уже после "nav", она так же является частью "header", но не является навигационным элементом

2024-07-02 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +        </main>
main тут не совсем корректно использовать для оборачивания form, совсем сильно ломается семантика.
Так же отсутствует закрывающий тег для header, полагаю, что конструкция будет следующая
```html
<header>
    <a href="#">В Мой блог</a> /* символ В мы потом стилизуем через иконку как картинку или текст с оформлением */
    <nav>    /* Тут будет уже список ul */   </nav>
    <form>  /* Инпут и иконка */   </form>
</header>
```

2024-07-02 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +    </section>
А вот это всё уже будет блоком "main" до footer

2024-07-02 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +        <div>FRONTEND &bull; 12 мая 2024</div>
Это у нас текстовый блок, поэтому мы можем использовать тут тег `p` - параграф вместо `div`, т.к. `div` - это у нас блочный элемент объединения контента, например было бы 2-3-4-5 блоков внутри и нам надо разместить всё это в одном блоке - тогда нам и приходит на помощь `div` или семантические блочные теги типа `section` или `article`

2024-07-02 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +        </section>
А вот эта секция как-то попала не на своё место, она идёт после "Теория цвета и т.п.

2024-07-02 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +        </div>
Вот тут так же, если читать "теги", то мы читаем следующее
Блочный элемент заголовка третьего уровня вложен в блочный элемент `div` единственным, т.е. блочное поведение у нас существует у обоих блоков, но не нужно было оборачивать заголовок отдельно в блок объединения контента, достаточно самостоятельного "заголовка", но и с заголовками "беда", ибо нарушена иерархия заголовков. Всегда первым будет заголовок первого уровня (h1 - в единственном экземпляре), далее следует уже h2 и т.п.

Однако, в этом случае вполне можно воспользоваться блочный текстовым элементом `p`

2024-07-02 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +    <h1>Теория цвета - Как цвет влияет на поведение потребителей</h1>
А вот это уже действительно по макету похоже на заголовок и использовать его так - верно, но надо вернуть на своё место)

2024-07-02 08:30 UTC, GitEsense commented on 2-Form/form.html
> +            </div>
Вполне имеет право на жизнь, но я бы воспользовался "параграфом", т.к. у нас идёт текст, а часть "Войти" выделена ссылкой аналогично выделению `span` внутри строки

2024-07-02 10:36 UTC, LizaY47 commented on 1-Blog/index.html
> +    </section>
хотелось бы небольшое уточнение, чтобы понять, почему именно здесь main

2024-07-09 13:21 UTC, GitEsense commented on 1-Blog/index.html
> +    </section>
> хотелось бы небольшое уточнение, чтобы понять, почему именно здесь main

Ну мы всё-таки разделяем семантически на "заголовок" и "основное" и "подвал", можно и без Мейн, но так у нас будет заголовок и подвал, а что в середине - просто блок , поэтому не плохо бы выдерживать семантику

2024-07-09 13:26 UTC, GitEsense approved these changes
Вот теперь всё отлично)

2024-07-09 13:26 UTC, GitEsense commented on 1-Blog/index.html
> +        зависимости от категории продукта) дают положительную или отрицательную оценку товару, основываясь только на его цвете.
Вот тут пропущен закрывающий тег `</p>`

2024-07-09 13:26 UTC, GitEsense commented on 1-Blog/index.html
> +        зависимости от категории продукта) дают положительную или отрицательную оценку товару, основываясь только на его цвете.
Для будущего удобства я бы рекомендовал все три параграфа положить в section / article (так стилизовать будет удобнее объединённый контент), не критично, но сильно будет удобнее

2024-07-15 11:12 UTC, merged